version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ER04TSDR*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
